import { describe, test, expect } from "bun:test";
import { verifySession, resolveSessionSecret, handleLogout, type OidcConfig } from "../auth-session.js";
import * as jose from "jose";

const SESSION_AUDIENCE = "prepalert:session";

function makeConfig(overrides?: Partial<OidcConfig>): OidcConfig {
  const secret = new TextEncoder().encode("test-session-secret-key-32bytes!!");
  return {
    issuer: "https://accounts.google.com",
    clientId: "test-client-id",
    clientSecret: "test-client-secret",
    allowedDomains: undefined,
    sessionSecret: secret,
    baseUrl: "http://localhost:8080",
    ...overrides,
  };
}

async function makeSessionCookie(
  claims: Record<string, unknown>,
  secret: Uint8Array,
  audience?: string,
): Promise<string> {
  return new jose.SignJWT(claims)
    .setProtectedHeader({ alg: "HS256" })
    .setAudience(audience ?? SESSION_AUDIENCE)
    .setExpirationTime("1h")
    .setIssuedAt()
    .sign(secret);
}

function makeRequest(cookie?: string): Request {
  const headers: Record<string, string> = {};
  if (cookie) {
    headers["cookie"] = `prepalert_session=${cookie}`;
  }
  return new Request("http://localhost:8080/api/sessions", { headers });
}

describe("verifySession", () => {
  test("returns payload for valid session cookie", async () => {
    const config = makeConfig();
    const token = await makeSessionCookie(
      { sub: "user123", email: "user@kayac.com", name: "Test User" },
      config.sessionSecret,
    );
    const result = await verifySession(makeRequest(token), config);
    expect(result).not.toBeNull();
    expect(result!.sub).toBe("user123");
    expect(result!.email).toBe("user@kayac.com");
    expect(result!.name).toBe("Test User");
  });

  test("returns null when no cookie", async () => {
    const config = makeConfig();
    const result = await verifySession(makeRequest(), config);
    expect(result).toBeNull();
  });

  test("returns null for expired token", async () => {
    const config = makeConfig();
    const token = await new jose.SignJWT({ sub: "user123", email: "user@kayac.com" })
      .setProtectedHeader({ alg: "HS256" })
      .setAudience(SESSION_AUDIENCE)
      .setExpirationTime("0s")
      .setIssuedAt()
      .sign(config.sessionSecret);
    await new Promise(resolve => setTimeout(resolve, 1100));
    const result = await verifySession(makeRequest(token), config);
    expect(result).toBeNull();
  });

  test("returns null for wrong secret", async () => {
    const config = makeConfig();
    const wrongSecret = new TextEncoder().encode("wrong-secret-key-needs-32-bytes!");
    const token = await makeSessionCookie(
      { sub: "user123", email: "user@kayac.com" },
      wrongSecret,
    );
    const result = await verifySession(makeRequest(token), config);
    expect(result).toBeNull();
  });

  test("returns null for wrong audience", async () => {
    const config = makeConfig();
    const token = await makeSessionCookie(
      { sub: "user123", email: "user@kayac.com" },
      config.sessionSecret,
      "prepalert:export",
    );
    const result = await verifySession(makeRequest(token), config);
    expect(result).toBeNull();
  });

  test("returns null when email claim is missing", async () => {
    const config = makeConfig();
    const token = await makeSessionCookie(
      { sub: "user123" },
      config.sessionSecret,
    );
    const result = await verifySession(makeRequest(token), config);
    expect(result).toBeNull();
  });

  test("handles name being absent", async () => {
    const config = makeConfig();
    const token = await makeSessionCookie(
      { sub: "user123", email: "user@kayac.com" },
      config.sessionSecret,
    );
    const result = await verifySession(makeRequest(token), config);
    expect(result).not.toBeNull();
    expect(result!.name).toBeUndefined();
  });
});

describe("resolveSessionSecret", () => {
  test("uses configured secret", () => {
    const result = resolveSessionSecret("my-session-secret");
    expect(result.autoGenerated).toBe(false);
  });

  test("auto-generates when undefined", () => {
    const result = resolveSessionSecret(undefined);
    expect(result.autoGenerated).toBe(true);
    expect(result.key.length).toBe(32);
  });

  test("auto-generates unique keys", () => {
    const a = resolveSessionSecret(undefined);
    const b = resolveSessionSecret(undefined);
    expect(a.key).not.toEqual(b.key);
  });
});

describe("handleLogout", () => {
  test("returns redirect with cleared cookie", () => {
    const response = handleLogout("http://localhost:8080");
    expect(response.status).toBe(302);
    expect(response.headers.get("location")).toBe("/");
    const cookie = response.headers.get("set-cookie");
    expect(cookie).toContain("prepalert_session=;");
    expect(cookie).toContain("Max-Age=0");
  });
});
