import { describe, test, expect } from "bun:test";
import { resolveExportSecret, generateExportToken, verifyExportToken } from "../export-token.js";

describe("resolveExportSecret", () => {
  test("uses configured secret", () => {
    const result = resolveExportSecret("my-secret");
    expect(result.autoGenerated).toBe(false);
    expect(new TextDecoder().decode(result.key)).toBe("my-secret");
  });

  test("auto-generates when undefined", () => {
    const result = resolveExportSecret(undefined);
    expect(result.autoGenerated).toBe(true);
    expect(result.key.length).toBeGreaterThan(0);
  });

  test("auto-generates unique keys", () => {
    const a = resolveExportSecret(undefined);
    const b = resolveExportSecret(undefined);
    expect(new TextDecoder().decode(a.key)).not.toBe(new TextDecoder().decode(b.key));
  });
});

describe("generateExportToken / verifyExportToken", () => {
  const secret = new TextEncoder().encode("test-secret-key");

  test("generates and verifies a valid token", async () => {
    const token = await generateExportToken("session-123", secret);
    expect(typeof token).toBe("string");
    expect(token.length).toBeGreaterThan(0);

    const sessionId = await verifyExportToken(token, secret);
    expect(sessionId).toBe("session-123");
  });

  test("returns null for invalid token", async () => {
    const result = await verifyExportToken("invalid-token", secret);
    expect(result).toBeNull();
  });

  test("returns null for wrong secret", async () => {
    const token = await generateExportToken("session-123", secret);
    const wrongSecret = new TextEncoder().encode("wrong-secret");
    const result = await verifyExportToken(token, wrongSecret);
    expect(result).toBeNull();
  });

  test("returns null for expired token", async () => {
    const token = await generateExportToken("session-123", secret, "0s");
    await new Promise(resolve => setTimeout(resolve, 1100));
    const result = await verifyExportToken(token, secret);
    expect(result).toBeNull();
  });
});
