import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");

async function collectFiles(dir: string): Promise<Record<string, string>> {
  const result: Record<string, string> = {};
  const entries = await readdir(dir, { recursive: true });
  for (const entry of entries) {
    if (!entry.endsWith(".md")) continue;
    const fullPath = join(dir, entry);
    const s = await stat(fullPath);
    if (!s.isFile()) continue;
    const content = await readFile(fullPath, "utf-8");
    result[entry] = content;
  }
  return result;
}

const docsDir = join(ROOT, "docs", "spec");
const skillsDir = join(ROOT, "skills");

const [docs, skills] = await Promise.all([
  collectFiles(docsDir),
  collectFiles(skillsDir),
]);

const output = `// Auto-generated by scripts/embed-assets.ts — do not edit
export const EMBEDDED_DOCS: Record<string, string> = ${JSON.stringify(docs)};
export const EMBEDDED_SKILLS: Record<string, string> = ${JSON.stringify(skills)};
`;

await writeFile(join(ROOT, "src", "embedded-assets.ts"), output);
console.log(`Embedded ${Object.keys(docs).length} docs files, ${Object.keys(skills).length} skills files`);
