import * as jose from "jose";
import { parseDuration } from "./config.js";

const ALG = "HS256";
export const DEFAULT_EXPIRES_IN = "15m";
const EXPORT_AUDIENCE = "prepalert:export";
const MIN_SECRET_BYTES = 32;

/**
 * Resolves the effective export token expiry in milliseconds, mirroring the
 * duration passed to generateExportToken so `expiresAt` stays accurate.
 */
export function exportTokenExpiresInMs(expiresIn: string = DEFAULT_EXPIRES_IN): number {
  return parseDuration(expiresIn) * 1000;
}

/**
 * Resolves the export secret key.
 * If configured, uses the provided secret. Otherwise generates a random one.
 * Returns the key as Uint8Array and whether it was auto-generated.
 * @throws {Error} if the configured secret is shorter than {@link MIN_SECRET_BYTES}.
 */
export function resolveExportSecret(configured: string | undefined): { key: Uint8Array; autoGenerated: boolean } {
  if (configured) {
    const key = new TextEncoder().encode(configured);
    if (key.length < MIN_SECRET_BYTES) {
      throw new Error(`secret must be at least ${MIN_SECRET_BYTES} bytes (got ${key.length})`);
    }
    return { key, autoGenerated: false };
  }
  const key = new Uint8Array(32);
  crypto.getRandomValues(key);
  return { key, autoGenerated: true };
}

/**
 * Generates a signed JWT for session export.
 * The token encodes the session ID and has a limited lifetime.
 */
export async function generateExportToken(sessionId: string, secret: Uint8Array, expiresIn?: string): Promise<string> {
  return new jose.SignJWT({ sid: sessionId })
    .setProtectedHeader({ alg: ALG })
    .setAudience(EXPORT_AUDIENCE)
    .setExpirationTime(expiresIn ?? DEFAULT_EXPIRES_IN)
    .setIssuedAt()
    .sign(secret);
}

/**
 * Verifies an export token and returns the session ID.
 * Returns null if the token is invalid or expired.
 */
export async function verifyExportToken(token: string, secret: Uint8Array): Promise<string | null> {
  try {
    const { payload } = await jose.jwtVerify(token, secret, { audience: EXPORT_AUDIENCE });
    const sid = payload["sid"];
    if (typeof sid !== "string") return null;
    return sid;
  } catch {
    return null;
  }
}
